# YouTube Analysis Pipeline Configuration

# Data paths
output_dir: "data"
intermediate_dir: "../../../data/intermediate/youtube_analysis"
citations_data_path: "../../../data/intermediate/cleaned_arena_data/citations.parquet"

# YouTube API configuration
youtube_api_key_env_var: "YOUTUBE_API_KEY"  # Environment variable name
api_batch_size: 50  # Maximum batch size for YouTube API (50 videos/channels per request)
rate_limit_delay: 1.0  # Seconds to wait between API requests

# API quotas and limits (for reference)
# YouTube Data API v3 default quota: 10,000 units/day
# Cost per request:
#   - videos.list: 1 unit per request, each request can contain up to 50 videos
#   - channels.list: 1 unit per request, each request can contain up to 50 channels
# Estimated usage:
#   - ~19,749 videos = ~394.98 units (50 videos per request)
#   - ~5,000-10,000 channels = ~100-200 units (50 channels per request)
#   - Total: ~600 units

# Data processing settings
max_description_length: 500  # Truncate descriptions to save space
preserve_raw_responses: true  # Store raw API responses for debugging
chunk_size: 1000  # Process videos/channels in chunks for memory efficiency

# Error handling
max_retries: 3  # Maximum API retry attempts
retry_delay: 5.0  # Base delay for exponential backoff (seconds)
continue_on_api_errors: true  # Continue processing even if some API calls fail